// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCrkNmncUIv-guBDKNO4mMCxwBPUn6zf8',
    appId: '1:336832482118:web:7cf898cb57177930f87347',
    messagingSenderId: '336832482118',
    projectId: 'ahmed-karam',
    authDomain: 'ahmed-karam.firebaseapp.com',
    storageBucket: 'ahmed-karam.firebasestorage.app',
    measurementId: 'G-MDQR0XMNSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2JCmX3q71N9lEGhOtxmYS-cd028JAFcs',
    appId: '1:336832482118:android:9ec7b6a355439ca1f87347',
    messagingSenderId: '336832482118',
    projectId: 'ahmed-karam',
    storageBucket: 'ahmed-karam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2VeA4LZEBVh978pexN215r7SCGeBEwJQ',
    appId: '1:336832482118:ios:10e6cc4d4fe3ffe8f87347',
    messagingSenderId: '336832482118',
    projectId: 'ahmed-karam',
    storageBucket: 'ahmed-karam.firebasestorage.app',
    iosBundleId: 'com.example.ahmedKaram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2VeA4LZEBVh978pexN215r7SCGeBEwJQ',
    appId: '1:336832482118:ios:10e6cc4d4fe3ffe8f87347',
    messagingSenderId: '336832482118',
    projectId: 'ahmed-karam',
    storageBucket: 'ahmed-karam.firebasestorage.app',
    iosBundleId: 'com.example.ahmedKaram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCrkNmncUIv-guBDKNO4mMCxwBPUn6zf8',
    appId: '1:336832482118:web:29c90d867de63376f87347',
    messagingSenderId: '336832482118',
    projectId: 'ahmed-karam',
    authDomain: 'ahmed-karam.firebaseapp.com',
    storageBucket: 'ahmed-karam.firebasestorage.app',
    measurementId: 'G-F8W4DBZTGX',
  );
}
